---
title: "A reproducible report of covid-19 spread for Australians"
author: "[Anthony Davidson](https://github.com/davan690)"
date: "`r format(Sys.time(), '%d %B %Y')`"
site: bookdown::bookdown_site
mail: "dynamicmodellingfromecology@gmail.com"
# !!! linkedin: "yan-holtz-2477534a"
twitter: "antsStats"
github: "apeco2020"
home: "www.ssnhub.com"
# !!! You need to provide a logo image here !!! Or just delete the field for no logo
logo: "logo_gallery.png"
output:
  epuRate::epurate:
    toc: TRUE
    number_sections: FALSE
    code_folding: "hide"
---

<br><br>

> The current output of this report is `r format(Sys.time(), '%d %B %Y')`. This doesnt  not garentte the data from the sources are upto date. Feel free to fund this project to insure someone can valiadate this.

ADDITIONALLY: This is NOT a list of what to do. Listen to your local organisations. This website is intended to make it easier to understand the data and associated sources of your informationby linking the simple figure with all the raw information in an open-source structure.

```{r, message=FALSE, warning=FALSE}
# sets paths for computers with other software components
# this code block produces an enviroment warning
# but not sure how to sort depenancies still
# Feb2020

# myPaths <- .libPaths("C:/Program Files/R/R-3.6.2/library")
# myPaths <- c(myPaths)
# .libPaths(myPaths)  # add new path
# .libPaths()

library(tidyverse)
library(rmarkdown)    # You need this library to run this template.
library(epuRate)      # Install with devtools: install_github("holtzy/epuRate", force=TRUE)
```

# Data sources for COVID19 {.tabset}
***

> This reproducible format allows for the same results to be generated for multiple time intervals. Previously generated reports can beb found in the `github` repository that builds this website.

> This website only produces a single snapshot of the current data within the datasources referenced. It was built with Australian residents in mind. The data is sourced from other open-source projects currently (massive thankyou!!)

## Wuhan-2019-nCoV

[canghailan/Wuhan-2019-nCoV](https://github.com/canghailan/Wuhan-2019-nCoV)

## Cases, provided by JHU CSSE

[Novel Coronavirus (COVID-19) Cases, provided by JHU CSSE](https://github.com/CSSEGISandData/COVID-19)

## Real-time

To use real-time data on the Corona virus epidemic, read from the end points below:

- csv: https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.csv

- json: https://raw.githubusercontent.com/canghailan/Wuhan-2019-nCoV/master/Wuhan-2019-nCoV.json

# Shiny apps for COVID19 {.tabset}
***

## John Coene institute

<iframe src="https://shiny.john-coene.com/coronavirus/" width="100%" height="400px"></iframe>

## `ncov19` package

<iframe src="http://www.bcloud.org/e/" width="100%" height="400px"></iframe>

## COVID-19 Epi Curves

<iframe src="https://simonthelwall.shinyapps.io/covid19/" width="100%" height="400px"></iframe>

Created by Simon Thelwall

## John-Hopkins university

<iframe src="https://ayushpkumar.shinyapps.io/CoronaVirusDashboard/_w_e4c7a489/" width="150%" height="600px"></iframe>

## UK

<iframe src="https://tools.dataatomic.com/shiny/CoronaOutbreak/" width="100%" height="400px"></iframe>

## Switzerland

<iframe src="https://simsc.shinyapps.io/corona/" width="150%" height="400px"></iframe>

## Other `git` repositories

[These sites and new resources are growing by the hour.]("https://github.com/search?l=R&q=covid19&type=Repositories") 

# Data accessed
***

Australia specific data:

<iframe src="https://covid-19.wileam.com/#/AUS" width="150%" height="400px"></iframe>

## Detailed and live??

<iframe src="https://ayushpkumar.shinyapps.io/CoronaVirusDashboard/_w_e4c7a489/" width="150%" height="400px"></iframe>


## Key figures

The data is accessed from the following sources: